version: '3'
services:
  app:
    build: .
    image: cv-laravel_php
    container_name: cv-laravel_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
#    working_dir: /var/www
    volumes:
#      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cv-api
  webserver:
    image: nginx:alpine
    container_name: cv-laravel_nginx
    restart: unless-stopped
    tty: true
    ports:
#      - "8000:8989"
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - cv-api
networks:
  cv-api:
    external: true
    name: cv-api_default
