services:
  app:
    build: .
    image: cv-laravel_php
    container_name: cv-laravel_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
#    working_dir: /var/www
    volumes:
      - www-data:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - oe-cv
  webserver:
    image: nginx:alpine
    container_name: cv-laravel_nginx
    restart: unless-stopped
    tty: true
    ports:
#      - "8000:8989"
      - 8000:80
    volumes:
      - www-data:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - oe-cv
networks:
  oe-cv:
    external: true
    name: proxy_oe-cv
volumes:
  www-data:
